### ISSUE TITLE
Excel sheet for webassociates based on resumes collected in December

### ISSUE THREAD

**Issue by anujkhurana** [ajency/Recruitment#4]

**Comment by Tanvi-HR** [comment]
Done. 

Pls refer to the below link. 

https://drive.google.com/open?id=1gO2ntOQL5S3ODNJxZxwSS7qogm3c6RDua5_-BU9xGFY&authuser=0

**Comment by anujkhurana** [comment]
Looks good. Leaving the issue open as sending resumes from November
