### ISSUE TITLE
Spreadsheet review of managing resumes. Might need new columns and tweaking of existing columns. 

### ISSUE THREAD

**Issue by anujkhurana** [ajency/Recruitment#6]

**Comment by Tanvi-HR** [comment]
https://drive.google.com/open?id=1gO2ntOQL5S3ODNJxZxwSS7qogm3c6RDua5_-BU9xGFY&authuser=0

Prefer to update and follow same sheet. Created new sheets in the same file, added new resumes. Added 2 extra columns for "Comments after PI - Interviewer 1 & Interviewer 2".
