### ISSUE TITLE
Look for free ATS available if any

### ISSUE THREAD

**Issue by Tanvi-HR** [ajency/Recruitment#8]

**Comment by Tanvi-HR** [comment]
http://qandidate.com/how-it-works/

Found an Applicant Tracking System which we can start using for recruitment. Pls go through the features. I have signed up and login credentials are Username: tanvi@ajency.in Password: ajency#123 

Let me know what you feel @anujkhurana @avantih

**Comment by anujkhurana** [comment]
I have tried using them in the past with little success. Let's discuss if
there is something between excel and a full blown ATS

**Comment by anujkhurana** [comment]
https://www.zoho.com/recruit/tour.html

Let's sign up for this with the company email id workwithus@ajency.in

Once we have used it for a week and are convinced it fits our needs we can take the paid plan.

**Comment by Tanvi-HR** [comment]
Signed up. Free trail for 15 days. 

Username: workwithus@ajency.in
Password: Ajency#123
